spring.application.name=gasCorocora

# Database configuration 
spring.datasource.url=jdbc:postgresql://bpm_engine_db:5432/bpm_engine
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always

# Database configuration Credit_Request
CONNECTION_CREDIT_REQUEST=jdbc:postgresql://gas_corocora_request_db:5432/gas_corocora_request
USER_DB=postgres
PASSWORD_DB=postgres

# *************************************************************************************************************************************

# Camunda configuration
camunda.bpm.database.type=postgres
camunda.bpm.database.schema-update=true
camunda.bpm.admin-user.id=demo
camunda.bpm.admin-user.password=demo
# Evita que pida crear usuario inicial
camunda.bpm.auto-deployment-enabled=true
#camunda.bpm.deployment-resource-pattern=classpath*:*.bpmn

# Camunda logs
logging.level.org.camunda.bpm.engine.impl.persistence.entity=DEBUG
logging.level.org.camunda.bpm.engine.impl.history.event=TRACE

# Local/demo maintenance
app.camunda.pause-automatic-monitoring=true

# Port configuration
server.port=9000

# Email configuration
email.sender=${EMAIL_ADDRESS:securedigitaldocs@gmail.com}
email.password=${EMAIL_PASSWORD:ijznbalxcqxzylty}
