spring.application.name=centralSys

# Database configuration 
spring.datasource.url=jdbc:postgresql://gas_corocora_request_db:5432/gas_corocora_request
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


API_URL=http://bpmengine:9000/engine-rest/

# Camunda API Configuration
camunda.url.start=http://bpmengine:9000/engine-rest/process-definition/key/MSGF-CreditResquest/start

# Port configuration
server.port=9003

server.error.whitelabel.enabled=false